# Generated by Django 5.0.6 on 2024-10-30 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_details_user_type_alter_details_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='details',
        ),
    ]
