# Generated by Django 5.0.6 on 2024-11-07 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='user',
        ),
        migrations.AddField(
            model_name='feedback',
            name='email',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
