# Generated by Django 5.0.6 on 2024-11-07 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_remove_feedback_user_feedback_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='feedback_status',
        ),
    ]
