# Generated by Django 5.1.1 on 2024-11-19 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_remove_feedback_feedback_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='emotion_analysis',
            name='emotion_type',
            field=models.CharField(default=None, max_length=10),
        ),
    ]
