# Generated by Django 5.1.1 on 2024-10-09 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='psychometric_question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('choice_1', models.CharField(max_length=225)),
                ('choice_2', models.CharField(max_length=225)),
                ('choice_3', models.CharField(max_length=225)),
                ('choice_4', models.CharField(max_length=225)),
                ('correct_answer', models.CharField(max_length=225)),
                ('question_status', models.BooleanField(default=True)),
            ],
        ),
    ]
