# Generated by Django 5.1.1 on 2024-10-11 12:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Psychometric', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Users_answers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q1', models.CharField(max_length=10)),
                ('q2', models.CharField(max_length=10)),
                ('q3', models.CharField(max_length=10)),
                ('q4', models.CharField(max_length=10)),
                ('q5', models.CharField(max_length=10)),
                ('q6', models.CharField(max_length=10)),
                ('q7', models.CharField(max_length=10)),
                ('q8', models.CharField(max_length=10)),
                ('q9', models.CharField(max_length=10)),
                ('q10', models.CharField(max_length=10)),
                ('response_status', models.BooleanField(default=True)),
                ('User_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
